// Generated by gencpp from file arebot_control/BusOp.msg
// DO NOT EDIT!


#ifndef AREBOT_CONTROL_MESSAGE_BUSOP_H
#define AREBOT_CONTROL_MESSAGE_BUSOP_H

#include <ros/service_traits.h>


#include <arebot_control/BusOpRequest.h>
#include <arebot_control/BusOpResponse.h>


namespace arebot_control
{

struct BusOp
{

typedef BusOpRequest Request;
typedef BusOpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BusOp
} // namespace arebot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arebot_control::BusOp > {
  static const char* value()
  {
    return "f42be7da85859f0e278c64aea47889c1";
  }

  static const char* value(const ::arebot_control::BusOp&) { return value(); }
};

template<>
struct DataType< ::arebot_control::BusOp > {
  static const char* value()
  {
    return "arebot_control/BusOp";
  }

  static const char* value(const ::arebot_control::BusOp&) { return value(); }
};


// service_traits::MD5Sum< ::arebot_control::BusOpRequest> should match
// service_traits::MD5Sum< ::arebot_control::BusOp >
template<>
struct MD5Sum< ::arebot_control::BusOpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arebot_control::BusOp >::value();
  }
  static const char* value(const ::arebot_control::BusOpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arebot_control::BusOpRequest> should match
// service_traits::DataType< ::arebot_control::BusOp >
template<>
struct DataType< ::arebot_control::BusOpRequest>
{
  static const char* value()
  {
    return DataType< ::arebot_control::BusOp >::value();
  }
  static const char* value(const ::arebot_control::BusOpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arebot_control::BusOpResponse> should match
// service_traits::MD5Sum< ::arebot_control::BusOp >
template<>
struct MD5Sum< ::arebot_control::BusOpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arebot_control::BusOp >::value();
  }
  static const char* value(const ::arebot_control::BusOpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arebot_control::BusOpResponse> should match
// service_traits::DataType< ::arebot_control::BusOp >
template<>
struct DataType< ::arebot_control::BusOpResponse>
{
  static const char* value()
  {
    return DataType< ::arebot_control::BusOp >::value();
  }
  static const char* value(const ::arebot_control::BusOpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AREBOT_CONTROL_MESSAGE_BUSOP_H
