// Generated by gencpp from file arebot_control/BusOpRequest.msg
// DO NOT EDIT!


#ifndef AREBOT_CONTROL_MESSAGE_BUSOPREQUEST_H
#define AREBOT_CONTROL_MESSAGE_BUSOPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arebot_control
{
template <class ContainerAllocator>
struct BusOpRequest_
{
  typedef BusOpRequest_<ContainerAllocator> Type;

  BusOpRequest_()
    : bus_id(0)
    , recv_len(0)
    , data()  {
    }
  BusOpRequest_(const ContainerAllocator& _alloc)
    : bus_id(0)
    , recv_len(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _bus_id_type;
  _bus_id_type bus_id;

   typedef uint8_t _recv_len_type;
  _recv_len_type recv_len;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::arebot_control::BusOpRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arebot_control::BusOpRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BusOpRequest_

typedef ::arebot_control::BusOpRequest_<std::allocator<void> > BusOpRequest;

typedef boost::shared_ptr< ::arebot_control::BusOpRequest > BusOpRequestPtr;
typedef boost::shared_ptr< ::arebot_control::BusOpRequest const> BusOpRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arebot_control::BusOpRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arebot_control::BusOpRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arebot_control::BusOpRequest_<ContainerAllocator1> & lhs, const ::arebot_control::BusOpRequest_<ContainerAllocator2> & rhs)
{
  return lhs.bus_id == rhs.bus_id &&
    lhs.recv_len == rhs.recv_len &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arebot_control::BusOpRequest_<ContainerAllocator1> & lhs, const ::arebot_control::BusOpRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arebot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arebot_control::BusOpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arebot_control::BusOpRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arebot_control::BusOpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arebot_control::BusOpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arebot_control::BusOpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arebot_control::BusOpRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arebot_control::BusOpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fda2775269fdf0be82c797ced44c6ef9";
  }

  static const char* value(const ::arebot_control::BusOpRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfda2775269fdf0beULL;
  static const uint64_t static_value2 = 0x82c797ced44c6ef9ULL;
};

template<class ContainerAllocator>
struct DataType< ::arebot_control::BusOpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arebot_control/BusOpRequest";
  }

  static const char* value(const ::arebot_control::BusOpRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arebot_control::BusOpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 bus_id\n"
"uint8 recv_len\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::arebot_control::BusOpRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arebot_control::BusOpRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bus_id);
      stream.next(m.recv_len);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BusOpRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arebot_control::BusOpRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arebot_control::BusOpRequest_<ContainerAllocator>& v)
  {
    s << indent << "bus_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bus_id);
    s << indent << "recv_len: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recv_len);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AREBOT_CONTROL_MESSAGE_BUSOPREQUEST_H
